# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-14 09:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20170114_1046'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=b''),
        ),
    ]
